apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
  namespace: demo
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello
  type: ClusterIP
