apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-ds
  name: hello-ds
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-ds
  type: NodePort
status:
  loadBalancer: {}
